# Generated by Django 3.1.6 on 2021-02-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Thought',
        ),
        migrations.RenameField(
            model_name='thought',
            old_name='name',
            new_name='thought',
        ),
    ]
